[project]
name = "todo-client"
version = "0.1.0"
description = "A client for keeping track of tasks"
dependencies = ["todo-common", "prettytable>=3.16.0"]

[project.scripts]
todo-client = "todo_client.main:main"

[build-system]
requires = ["uv_build>=0.9.8,<0.10.0"]
build-backend = "uv_build"
